.TH SERVICEMASTER 1 "ServiceMaster 1.7.7" "User Commands" "ServiceMaster 1.7.7"
.SH NAME
ServiceMaster \- A powerful tool for managing systemd units.
.SH SYNOPSIS
.B servicemaster
[\fIOPTION\fR]...
.SH DESCRIPTION
\fBServiceMaster\fR is a powerful terminal-based tool for managing systemd units on Linux systems. It provides an intuitive interface for viewing and controlling system and user units, making it easier to manage your units without leaving the command line.

.SH FEATURES
.IP \[bu] 2
View all systemd units or filter by type (services, devices, sockets, etc.).
.IP \[bu] 2
Start, stop, restart, enable, disable, mask, and unmask units.
.IP \[bu] 2
View detailed status information for each unit.
.IP \[bu] 2
Switch between system and user units.
.IP \[bu] 2
User-friendly ncurses interface with color-coded information.
.IP \[bu] 2
Keyboard shortcuts for quick navigation and control.
.IP \[bu] 2
DBus event loop: Reacts immediately to external changes to units.
.IP \[bu] 2
Switch between colorschemes, edit or add colorschemes.
.IP \[bu] 2
Easy configuration with Toml file.
.IP \[bu] 2
Search for units by name.
.IP \[bu] 2
Sort units by different columns (unit name, state, active, sub, description).

.SH REQUIREMENTS
.IP \[bu] 2
Linux system with Systemd.
.IP \[bu] 2
ncurses library.
.IP \[bu] 2
Systemd development libraries.

.SH USAGE
After launching \fBServiceMaster\fR, you can use the following controls:
.IP \[bu] 2
Arrow keys (hljk), page up/down: Navigate through the list of units.
.IP \[bu] 2
Space: Toggle between system and user units.
.IP \[bu] 2
Enter: Show detailed status of the selected unit.
.IP \[bu] 2
F1-F8: Perform actions (start, stop, restart, etc.) on the selected unit.
.IP \[bu] 2
a-z: Quick filter units by type.
.IP \[bu] 2
q or ESC: Quit the application.
.IP \[bu] 2
+,-: Switch between colorschemes.
.IP \[bu] 2
f: Search for units by name.
.IP \[bu] 2
Tab: Select column header, Return: Sort by selected column.

.SH CLI OPTIONS
.IP \[bu] 2
-v: Display the version information and exit.
.IP \[bu] 2
-w: Do not show the welcome message.
.IP \[bu] 2
-h: Display help / usage message and exit.
.IP \[bu] 2
-c: Set the colorscheme.
    Names with a space must be enclosed in quotes!
.IP \[bu] 2
-l: List all available colorschemes.
.IP \[bu] 2
-p: Print configuration file (with colorschemes).
.IP \[bu] 2
-e: Edit the configuration file.

.SH CONFIGURATION
The configuration file is located at /etc/servicemaster/servicemaster.toml
.PP
You can edit it with:
.PP
.B servicemaster -e
.PP
Print the configuration file with:
.PP
.B servicemaster -p

.SH COLORSCHEMES
You can add your own colorschemes to the configuration file or change the existing ones.
.PP
List all available colorschemes with:
.PP
.B servicemaster -l
.PP
Switch between colorschemes using the '+' and '-' keys.

.SH SECURITY NOTE
For security reasons, only root can manipulate system units, and only user units can be manipulated when running as a regular user.

.SH LICENSE
This project is licensed under the MIT License. See the LICENSE file for details.
The Toml library is also licensed under the MIT License. See the lib/toml.h file for details.

.SH AUTHOR
Lennart Martens

.SH CONTACT
For bug reports, feature requests, or general inquiries:
.IP \[bu] 2
Email: monkeynator78@gmail.com
.IP \[bu] 2
GitHub: https://github.com/lennart1978/servicemaster

.SH VERSION
1.7.7 (2025)
